// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConsoleOutput():Promise<string>;

export function GetReport(arg1:string):Promise<string>;

export function GetReports():Promise<string>;

export function RunCommand(arg1:string):Promise<void>;
