// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConsoleOutput() {
  return window['go']['main']['App']['GetConsoleOutput']();
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetReports() {
  return window['go']['main']['App']['GetReports']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}
